name: storage_contract
description: A base contract/abstraction for building pure storage.
version: 0.0.1
homepage: https://ampersanda.dev

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
